---  
 - name: create the file repository configuration
   command: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
   
 - name: import the repository signing key
   apt_key: 
     url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
     state: present
     
 - name: updating system
   apt:
     upgrade: yes
      
 - name: installing postgresql
   apt: 
     name: postgresql-10 
     state: latest
   
 - name: enabling PostgreSQL on boot and starting it
   systemd: 
     name: postgresql
     state: started
     enabled: yes
